// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmG4sbJrk2V9gtHPtClibSDYkHw2llNGQ',
    appId: '1:1029508787980:web:68c684bb98e4fbf78ae329',
    messagingSenderId: '1029508787980',
    projectId: 'dolatdigital-8e312',
    authDomain: 'dolatdigital-8e312.firebaseapp.com',
    storageBucket: 'dolatdigital-8e312.firebasestorage.app',
    measurementId: 'G-L0D43BKRV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEINKq3r9kHwOo-DG6EWMoBxZIiliSTxQ',
    appId: '1:1029508787980:android:d7002d5e724350cd8ae329',
    messagingSenderId: '1029508787980',
    projectId: 'dolatdigital-8e312',
    storageBucket: 'dolatdigital-8e312.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg-MButIi8i_OCSG-Sam_4AW8SEQGYHqY',
    appId: '1:1029508787980:ios:03b729427d1460558ae329',
    messagingSenderId: '1029508787980',
    projectId: 'dolatdigital-8e312',
    storageBucket: 'dolatdigital-8e312.firebasestorage.app',
    iosBundleId: 'com.dolatdigital.dolatDigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg-MButIi8i_OCSG-Sam_4AW8SEQGYHqY',
    appId: '1:1029508787980:ios:03b729427d1460558ae329',
    messagingSenderId: '1029508787980',
    projectId: 'dolatdigital-8e312',
    storageBucket: 'dolatdigital-8e312.firebasestorage.app',
    iosBundleId: 'com.dolatdigital.dolatDigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmG4sbJrk2V9gtHPtClibSDYkHw2llNGQ',
    appId: '1:1029508787980:web:f9cedd68b65c64c78ae329',
    messagingSenderId: '1029508787980',
    projectId: 'dolatdigital-8e312',
    authDomain: 'dolatdigital-8e312.firebaseapp.com',
    storageBucket: 'dolatdigital-8e312.firebasestorage.app',
    measurementId: 'G-V2WSD9DL03',
  );
}
